# Generated by Django 3.2.16 on 2023-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_subscription_services_su_field_a_155836_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='field_a',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='field_b',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
